model:
  base_learning_rate: 2e-4
  target: unimumo.models.motion_vqvae.MotionVQVAE
  params:
    monitor: "val/rec_loss"
    music_key: "waveform"
    motion_key: "motion"
    loss_config:
      target: unimumo.modules.loss.MotionVqVaeLoss
      params:
        commitment_loss_weight: 0.02
        motion_weight: 1.0
    motion_config:
      input_dim: 263
      output_dim: 128
      emb_dim_encoder: [ 256, 224, 192, 144, 128 ]
      emb_dim_decoder: [ 128, 144, 192, 224, 256 ]
      input_fps: 20
      rvq_fps: 50
      dilation_growth_rate: 2
      depth_per_res_block: 6
      activation: 'relu'
    music_config:
      vqvae_ckpt: '/gpfs/u/home/LMCG/LMCGnngn/scratch/yanghan/music_dance/weight/musicgen_vqvae.bin'
    pre_post_quantize_config:
      pre_quant_conv_mult: 4
      post_quant_conv_mult: 4


data:
  target: mm_vqvae_train.DataModuleFromConfig
  params:
    batch_size: 30
    wrap: True
    train:
      target: unimumo.data.music_motion_dataset.MusicMotionDataset
      params:
        split: "train"
        music_dir: '/gpfs/u/home/LMCG/LMCGnngn/scratch/yanghan/music4all/audios'
        motion_dir: '/gpfs/u/home/LMCG/LMCGnngn/scratch/yanghan/music_dance/motion_data'
        music_meta_dir: '/gpfs/u/home/LMCG/LMCGnngn/scratch/yanghan/music4all/'
        music_beat_dir: '/gpfs/u/home/LMCG/LMCGnngn/scratch/yanghan/music4all/music4all_beat'
        duration: 5
        use_humanml3d: True
        music_dataset_name: 'music4all'
        traverse_motion: True
        align: True

    validation:
      target: unimumo.data.music_motion_dataset.MusicMotionDataset
      params:
        split: "val"
        music_dir: '/gpfs/u/home/LMCG/LMCGnngn/scratch/yanghan/music4all/audios'
        motion_dir: '/gpfs/u/home/LMCG/LMCGnngn/scratch/yanghan/music_dance/motion_data'
        music_meta_dir: '/gpfs/u/home/LMCG/LMCGnngn/scratch/yanghan/music4all/'
        music_beat_dir: '/gpfs/u/home/LMCG/LMCGnngn/scratch/yanghan/music4all/music4all_beat'
        duration: 5
        use_humanml3d: True
        music_dataset_name: 'music4all'
        traverse_motion: True
        align: True


lightning:
  callbacks:
    video_logger:
      target: unimumo.joint_vae_logger.MusicMotionLogger
      params:
        batch_frequency: 7000
        max_videos: 4
        increase_log_steps: True
        #motion_dir: 'D:/local_documentation/deep_learning/ChuangGan/motion_data'
        motion_dir: '/gpfs/u/home/LMCG/LMCGnngn/scratch/yanghan/music_dance/motion_data'

  trainer:
    benchmark: True
    gpus: "0,1,2,3"
    num_nodes: 2
