model:
  base_learning_rate: 5e-5
  target: unimumo.models.transformer_model.MusicMotionTransformer
  params:
    name: '/gpfs/u/home/LMCG/LMCGnngn/scratch/yanghan/music_dance/weight/musicgen_small.bin'
    music_key: 'music_code'
    motion_key: 'motion_code'
    text_cond_key: 'text'
    motion_weight: 0.1
    length_single_modal: 500
    feature_frame_rate: 50

    monitor: "val/loss"

    generation_params:
      use_sampling: True
      temp: 1.
      top_k: 250
      top_p: 0.0
      cfg_coef: 3.0
      duration: 10

    scheduler_config: # 10000 warmup steps
      target: unimumo.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps: [ 10000 ]
        cycle_lengths: [ 400000 ]
        f_start: [ 1.e-6 ]
        f_max: [ 1. ]
        f_min: [ 0. ]

    optimization_config:
      eager_sync: True
      max_norm: 1.0
      learning_rate: 5e-5
      betas: [0.9, 0.95]
      weight_decay: 0.1
      eps: 1e-8

    text_model_config:
      target: unimumo.models.text_generation_model.TextGenerator
      params:
        model: '/gpfs/u/home/LMCG/LMCGnngn/scratch/yanghan/music_dance/weight/T5BaseForConditionalGeneration'
        max_length: 64
        context_dim: 1024
        self_dim: 768

data:
  target: train.DataModuleFromConfig
  params:
    batch_size_music_motion: 3
    batch_size_caption: 8
    wrap: True
    num_workers: 4
    train:
      target: unimumo.data.music_motion_text_dataset.MusicMotionTextDataset
      params:
        split: "train"
        music_meta_dir: '/gpfs/u/home/LMCG/LMCGnngn/scratch/yanghan/music4all'
        motion_meta_dir: '/gpfs/u/home/LMCG/LMCGnngn/scratch/yanghan/music_dance/motion_data'
        music_code_dir: '/gpfs/u/home/LMCG/LMCGnngn/scratch/yanghan/music4all/music4all_codes'
        motion_code_dir: '/gpfs/u/home/LMCG/LMCGnngn/scratch/yanghan/music_dance/motion_data/aligned_motion_code_enlarged_new'
        duration: 10
        dropout_prob: 0.6
        vqvae_sr: 32000
        llama_caption_ratio: 0.3

    validation:
      target: unimumo.data.music_motion_text_dataset.MusicMotionTextDataset
      params:
        split: "val"
        music_meta_dir: '/gpfs/u/home/LMCG/LMCGnngn/scratch/yanghan/music4all'
        motion_meta_dir: '/gpfs/u/home/LMCG/LMCGnngn/scratch/yanghan/music_dance/motion_data'
        music_code_dir: '/gpfs/u/home/LMCG/LMCGnngn/scratch/yanghan/music4all/music4all_codes'
        motion_code_dir: '/gpfs/u/home/LMCG/LMCGnngn/scratch/yanghan/music_dance/motion_data/aligned_motion_code_enlarged_new'
        duration: 10
        dropout_prob: 0.6
        vqvae_sr: 32000
        llama_caption_ratio: 0.3

lightning:
  callbacks:
    video_logger:
      target: unimumo.loggers.MusicMotionLogger
      params:
        music_vqvae_path: '/gpfs/u/home/LMCG/LMCGnngn/scratch/yanghan/music_dance/weight/musicgen_vqvae.bin'
        motion_vqvae_path: '/gpfs/u/home/LMCG/LMCGnngn/scratch/yanghan/music_dance/weight/mm_vqvae.ckpt'
        motion_vqvae_config_path: '/gpfs/u/home/LMCG/LMCGnngn/scratch/yanghan/final_version_2/My_Tempt_Repo/configs/train_motion_vqvae.yaml'
        motion_dir: '/gpfs/u/home/LMCG/LMCGnngn/scratch/yanghan/music_dance/motion_data'
        epoch_frequency: 10
        batch_frequency: 2000
        max_video_per_generation: 4
        duration: 10
        sr: 32000
        max_video_logged: 120
        disabled: false
  trainer:
    benchmark: True
    devices: 6
    num_nodes: 8
    strategy: ddp
